Controllers/AdminIlacController.cs
using EczaneDEMOo.Models.Entities;
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Yonetici")]// Bu controller'ı sadece 'Yonetici' rolüne sahip kullanıcıların erişebilmesi için yetkilendirir
    public class AdminIlacController : Controller
    {
        EczaneContext _context;

        public AdminIlacController()
        {
            _context = new EczaneContext();
        }
        // GET: Ilac
        public ActionResult Index()
        {
            // silindiMi alanı false olan tüm ilaçları getir ve model olarak view'e gönder
            var model = _context.Ilac.Where(i => i.silindiMi == false).ToList();
            return View(model);
        }


        public ActionResult Sil(int id) 
        {
            // Verilen id'ye sahip ilacı veritabanından getir
            var ilac = _context.Ilac.Where(k => k.ilacID == id).SingleOrDefault();

            ilac.silindiMi = true;
            _context.SaveChanges();

            // Başarılı mesajını TempData'ya ekle
            TempData["SuccessMessage"] = "İlac başarılı bir şekilde silindi.";
            return RedirectToAction("Index");
        }
    }
}

Controllers/AdminReceteController.cs
using EczaneDEMOo.Models.Entities;
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Yonetici")]
    public class AdminReceteController : Controller
    {
        EczaneContext _context;

        public AdminReceteController()
        {
            _context = new EczaneContext();
        }
        // GET: AdminSatis
        public ActionResult Index()
        {
            // Recete tablosundaki tüm reçeteleri getir ve model olarak view'e gönder
            var model = _context.Recete.ToList();
            return View(model);
        }
    }
}

Controllers/AnasayfaController.cs
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Kullanici")]

    public class AnasayfaController : Controller
    {
        // GET: Anasayfa
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SatisController.cs
using EczaneDEMOo.Models;
using EczaneDEMOo.Models.Entities;
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Kullanici")]

    public class SatisController : Controller
    {
        private readonly EczaneContext _context;

        public SatisController()
        {
            _context = new EczaneContext();
        }

        // GET: Satis
        public ActionResult Index()
        {
            var model = _context.Satis.ToList();// Tüm satışları getirir ve listeye dönüştürür
            return View(model);
        }

        public ActionResult RecetesizSatis()
        {
            #region Ilac Getirme
            // İlaçları getir ve SelectListItem nesnelerine dönüştür
            List<SelectListItem> selectListItems = _context.Ilac.Select(f => new SelectListItem
            {
                Value = f.ilacID.ToString(),
                Text = f.ad
            }).ToList();

            // SelectList oluşturuluyor

            SelectList selectList = new SelectList(selectListItems, "Value", "Text");

            // İlaç bilgisi ViewData'ya ekleniyor
            ViewData["Ilac"] = selectList;
            #endregion
            return View();// RecetesizSatis view'ını döner
        }

        // GET: ReceteNo
        [HttpGet]
        public ActionResult ReceteNoGir()
        {
            return View();
        }

        // POST: ReceteNo
        [HttpPost]
        public ActionResult ReceteNoGir(string receteNo)// ReceteNoGir aksiyon metodu, string parametre alır
        {
            if (!string.IsNullOrEmpty(receteNo))// Reçete numarası boş değilse
            {
                // ReceteNo'ya ait bilgileri veritabanından alın
                var recete = _context.Recete.SingleOrDefault(r => r.receteNo == receteNo);
                if (recete != null)// Reçete bulunursa
                {
                    var model = new SatisReceteSatisViewModel
                    {
                        ReceteNo = recete.receteNo,// Reçetenin numarası (receteNo) modelin ReceteNo alanına atanıyor
                        ReceteID = recete.receteID,
                        IlacID = recete.ilacID.Value,
                        Adet = recete.miktar.Value,
                        Fiyat = recete.Ilac.fiyat.Value
                    };

                    // Bilgi ve onay sayfasına yönlendir
                    return View("ReceteBilgiOnay", model);
                }

                ModelState.AddModelError("", "Geçerli bir reçete numarası bulunamadı.");
                return View();
            }

            ModelState.AddModelError("", "Reçete numarası boş olamaz.");
            return View();
        }

        // POST: Onayla
        [HttpPost]
        public ActionResult Onayla(SatisReceteSatisViewModel model)
        {
            if (ModelState.IsValid)// ModelState geçerli mi kontrolü
            {
                var recete = _context.Recete.Where(r => r.receteID == model.ReceteID).SingleOrDefault();
                // Satış işlemini veritabanına kaydet
                // Yeni bir Satis nesnesi oluştur ve modelden gelen verilerle doldur
                var satis = new Satis
                {
                    receteID = model.ReceteID,// Modelden gelen ReceteID'yi ata
                    ilacID = model.IlacID,
                    miktar = model.Adet,
                    fiyat = model.Fiyat * model.Adet,
                    satisTarih = DateTime.Now
                };

                _context.Satis.Add(satis);// Yeni satış ekle
                _context.SaveChanges();// Değişiklikleri kaydet

                return RedirectToAction("SatisBasarili");
            }

            return View("ReceteBilgiOnay", model);
        }

        public ActionResult SatisBasarili()
        {
            return View();
        }

        // ReceteBilgiOnay görünümünü aynı şekilde bıraktık
        public ActionResult ReceteBilgiOnay()
        {
            return View();
        }

        public ActionResult Ilac()
        {

            return View();
        }

    }
}

Views/Shared/YoneticiLayout.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="tr">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ECZANE PROJESİ</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/fontawesome-free/css/all.min.css">
    <!-- IonIcons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/dist/css/adminlte.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Bootstrap Color Picker -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.min.css">
    <!-- Tempusdominus Bootstrap 4 -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css">
    <!-- Select2 -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/select2/css/select2.min.css">
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css">
    <!-- Bootstrap4 Duallistbox -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/bootstrap4-duallistbox/bootstrap-duallistbox.min.css">
    <!-- BS Stepper -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/bs-stepper/css/bs-stepper.min.css">
    <!-- dropzonejs -->
    <link rel="stylesheet" href="~/Theme/AdminPanel/plugins/dropzone/min/dropzone.min.css">
</head>
<!--
`body` tag options:

  Apply one or more of the following classes to to the body tag
  to get the desired effect

  * sidebar-collapse
  * sidebar-mini
-->
<body class="hold-transition sidebar-mini">
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                @*<li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>*@
            </ul>

            <!-- Right navbar links -->
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Logout","Account")" role="button">
                        <i class="fas fa-sign-out-alt"></i>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="@Url.Action("Index", "Yonetici")" class="brand-link">
                <img src="~/İmages/NXFK96YNSK33R6.jpg" alt="eLogo Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light"><b>ECZANE</b> Uygulama</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user panel (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/İmages/Logo.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Ömer KÖÇER</a>
                    </div>
                </div>

                <!-- SidebarSearch Form -->
                <div class="form-inline">
                    <div class="input-group" data-widget="sidebar-search">
                        <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                        <div class="input-group-append">
                            <button class="btn btn-sidebar">
                                <i class="fas fa-search fa-fw"></i>
                            </button>
                        </div>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <!-- Add icons to the links using the .nav-icon class with font-awesome or any other icon font library -->
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "Yonetici")" class="nav-link active">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Anasayfa</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "AdminKullanici")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Kullanıcı</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "AdminIlac")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>İlaç</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="@Url.Action("Index", "AdminRecete")" class="nav-link">
                                <i class="far fa-circle nav-icon"></i>
                                <p>Reçete Listesi</p>
                            </a>
                        </li>
                        @*<li class="nav-item">
            <a href="#" class="nav-link">
                <i class="nav-icon fas fa-table"></i>
                <p>
                    Tablolar
                    <i class="fas fa-angle-left right"></i>
                </p>
            </a>
            <ul class="nav nav-treeview">
                <li class="nav-item">
                    <a href="@Url.Action("ReceteliSatis", "Yönetici")" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>İşlemler</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("RecetesizSatis", "Satis")" class="nav-link">
                        <i class="far fa-circle nav-icon"></i>
                        <p>Reçetesiz İlaç Satış Tablosu</p>
                    </a>
                </li>
            </ul>
        </li>*@
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1 class="m-0"><b>ECZANE</b> UYGULAMASI</h1>
                        </div><!-- /.col -->
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item active">@ViewBag.Title</li>
                            </ol>
                        </div><!-- /.col -->
                    </div><!-- /.row -->
                </div><!-- /.container-fluid -->
            </div>
            <!-- /.content-header -->
            <!-- Main content -->
            @RenderBody()

            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            <!-- Control sidebar content goes here -->
        </aside>
        <!-- /.control-sidebar -->
        <!-- Main Footer -->
        @*<footer class="main-footer">
            <strong>Copyright &copy; 2021-2024 <a href="#">ECZANE UYGULAMASI</a>.</strong>
            All rights reserved.
            <div class="float-right d-none d-sm-inline-block">
                <b>Version</b> 3.2.0
            </div>*@
        </footer>
    </div>
    <!-- ./wrapper -->
    <!-- REQUIRED SCRIPTS -->
    <!-- jQuery -->
    <script src="~/Theme/AdminPanel/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap -->
    <script src="~/Theme/AdminPanel/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE -->
    <script src="~/Theme/AdminPanel/dist/js/adminlte.js"></script>

    <!-- OPTIONAL SCRIPTS -->
    <script src="~/Theme/AdminPanel/plugins/chart.js/Chart.min.js"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="~/Theme/AdminPanel/dist/js/pages/dashboard3.js"></script>

    <!-- DataTables  & Plugins -->
    <script src="~/Theme/AdminPanel/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/jszip/jszip.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/Theme/AdminPanel/dist/js/adminlte.min.js"></script>

    <!-- Select2 -->
    <script src="~/Theme/AdminPanel/plugins/select2/js/select2.full.min.js"></script>
    <!-- InputMask -->
    <script src="~/Theme/AdminPanel/plugins/moment/moment.min.js"></script>
    <script src="~/Theme/AdminPanel/plugins/inputmask/jquery.inputmask.min.js"></script>
    <!-- dropzonejs -->
    <!--<script src="~/Theme/AdminPanel/plugins/dropzone/min/dropzone.min.js"></script>-->

    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": false,
                "searching": false,
                "ordering": true,
                "info": true,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
</body>
</html>