Controllers/AdminKullaniciController.cs
using EczaneDEMOo.Models.Entities;
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Yonetici")]
    public class AdminKullaniciController : Controller
    {
        //Context Field
        EczaneContext _context;

        public AdminKullaniciController()
        {
            _context = new EczaneContext();
        }
        // GET: AdminKullanici
        public ActionResult Index()
        {
            // silindiMi alanı false olan tüm kullanıcıları getir ve model olarak view'e gönder
            var model = _context.Kullanici.Where(k => k.silindiMi == false).ToList();
            return View(model);
        }

        public ActionResult Ekle()// Ekle aksiyon metodu (GET isteği)
        {
            #region Rol Getirme
            // Kullanıcı rolleri getiriliyor ve SelectListItem nesnelerine dönüştürülüyor
            List<SelectListItem> selectListItems = _context.KullaniciRol.Select(f => new SelectListItem
            {
                Value = f.kullaniciRolID.ToString(),
                Text = f.ad
            }).ToList();

            // SelectList oluşturuluyor
            SelectList selectList = new SelectList(selectListItems, "Value", "Text");

            // Rol bilgisi ViewData'ya ekleniyor
            ViewData["Rol"] = selectList;
            #endregion

            // Yeni bir Kullanici nesnesi oluşturuluyor
            var model = new Kullanici();

            return View(model);
        }

        [HttpPost]
        public ActionResult Ekle(Kullanici kullanici)
        {
            if (ModelState.IsValid)// ModelState geçerli mi kontrolü
            {
                try
                {
                    using (var context = new EczaneContext())
                    {
                        // Yeni kullanıcı ekle ve değişiklikleri kaydet
                        context.Kullanici.Add(kullanici);
                        context.SaveChanges();
                    }
                    // Başarılı mesajını TempData'ya ekle
                    TempData["SuccessMessageEkleme"] = "Kullanıcı başarılı bir şekilde eklendi.";

                    
                    return RedirectToAction("Index");
                }
                catch (Exception ex)
                {
                    // Hata durumunda hatayı TempData'ya ekle
                    TempData["ErrorMessageEkleme"] = "Kullanıcı eklenirken bir hata oluştu: " + ex.Message;
                }
            }

            // Eğer model geçerli değilse veya işlem başarısız olursa, aynı sayfaya geri dönün
            return View(kullanici);
        }

        public ActionResult Duzenle(int id)
        {
            try
            {
                // Veritabanında kullanıcıyı bul
                var kullanici = _context.Kullanici.SingleOrDefault(k => k.kullaniciID == id);

                if (kullanici != null)
                {
                    #region Rol Getirme
                    // Kullanıcı rolleri getiriliyor ve SelectListItem nesnelerine dönüştürülüyor
                    List<SelectListItem> selectListItems = _context.KullaniciRol.Select(f => new SelectListItem
                    {
                        Value = f.kullaniciRolID.ToString(),
                        Text = f.ad
                    }).ToList();

                    // SelectList oluşturuluyor
                    SelectList selectList = new SelectList(selectListItems, "Value", "Text");

                    // Rol bilgisi ViewData'ya ekleniyor
                    ViewData["Rol"] = selectList;
                    #endregion

                    // Kullanıcıyı güncelleme sayfasına yönlendir
                    return View(kullanici);
                }
                // Kullanıcı bulunamadıysa hata mesajı göster
                TempData["ErrorMessage"] = "Kullanıcı bulunamadı.";

            }
            catch (Exception ex)
            {
                // Hata durumunda hata mesajını göster
                TempData["ErrorMessage"] = "Kullanıcı güncellenirken bir hata oluştu: " + ex.Message;
            }
            // Eğer ModelState geçerli değilse veya işlem başarısızsa aynı sayfaya dön
            return RedirectToAction("Index");

        }

        [HttpPost]
        public ActionResult Duzenle(int id, Kullanici model)
        {
            try
            {
                // Veritabanında kullanıcıyı bul
                var kullanici = _context.Kullanici.SingleOrDefault(k => k.kullaniciID == model.kullaniciID);

                if (kullanici is null)
                {
                    // Kullanıcı bulunamadıysa hata mesajı göster
                    TempData["ErrorMessage"] = "Kullanıcı bulunamadı.";
                    return View();
                }
                // Kullanıcıyı güncelle
                // 1. Adım: Veritabanı bağlamında (context) güncellenecek kullanıcıyı takip eden bir giriş (entry) nesnesi oluşturulur.
                var entry = _context.Entry(kullanici);
                // 2. Adım: Kullanıcının mevcut değerleri, güncelleme formundan gelen modelin değerleriyle değiştirilir.
                entry.CurrentValues.SetValues(model);
                // 3. Adım: Bu girişin (entry) durumunun (state) 'Modified' (değiştirildi) olarak işaretlenir, bu da Entity Framework'e bu nesnenin güncellenmesi gerektiğini belirtir.
                entry.State = EntityState.Modified;
                // 4. Adım: Veritabanına değişiklikleri kaydeder. Bu, kullanıcı bilgilerini veritabanında günceller.
                _context.SaveChanges();
                TempData["SuccesMessage"] = "Kullanıcı güncellenirken bir hata oluştu: ";

            }
            catch (Exception ex)
            {
                // Hata durumunda hata mesajını göster
                TempData["ErrorMessage"] = "Kullanıcı güncellenirken bir hata oluştu: " + ex.Message;
            }


            // Eğer ModelState geçerli değilse veya işlem başarısızsa aynı sayfaya dön
            return RedirectToAction("Index");

        }

        public ActionResult Sil(int id)
        {
            // Verilen id'ye sahip kullanıcıyı veritabanından getir
            var kullanici = _context.Kullanici.Where(k => k.kullaniciID == id).SingleOrDefault();

            // Kullanıcı bulunduysa, silindiMi alanını true yap
            kullanici.silindiMi = true;
            _context.SaveChanges();

            // Başarılı mesajını TempData'ya ekle
            TempData["SuccessMessage"] = "Kullanıcı başarılı bir şekilde silindi.";

            return RedirectToAction("Index");
        }
    }
}

Views/AdminKullanici/Duzenle.cshtml
@model EczaneDEMOo.Models.Entities.Kullanici

@{
    ViewBag.Title = "Düzenleme Sayfası";
    Layout = "~/Views/Shared/YoneticiLayout.cshtml";
}

<h2>Duzenle</h2>

@using (Html.BeginForm("Duzenle", "AdminKullanici", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kullanıcı Bilgileri</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.kullaniciID)

        <div class="form-group">
            @Html.LabelFor(model => model.rolID, "Rolü", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("rolID", (SelectList)ViewData["Rol"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.rolID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ad, "Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soyad, "Soyadı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soyad,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciAd, "Kullanıcı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kullaniciAd,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kullaniciAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sifre, "Şifresi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefon,"Telefon Numarası", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefon, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ePosta, "E Posta Adresi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ePosta,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ePosta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Listeye Geri Dön</a>
</div>

Views/AdminKullanici/Ekle.cshtml
@model EczaneDEMOo.Models.Entities.Kullanici

@{
    ViewBag.Title = "Ekle";
    Layout = "~/Views/Shared/YoneticiLayout.cshtml";
}

<h2>Ekle</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Kullanici</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.rolID, "Rolü", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("rolID", (SelectList)ViewData["Rol"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.rolID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ad, "Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ad,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.soyad, "Soyadı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.soyad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.soyad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.kullaniciAd, "Kullanıcı Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.kullaniciAd, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.kullaniciAd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.sifre, "Şifresi", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.sifre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.sifre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.telefon, "Telefon Numarası", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.telefon,  new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.telefon, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ePosta, "E Posta Adresi ", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ePosta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ePosta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Ekle" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Listeye Geri Dön</a>
</div>

Views/AdminKullanici/Index.cshtml
@model IEnumerable<EczaneDEMOo.Models.Entities.Kullanici>

@{
    ViewBag.Title = "Kullanıcı Görüntüleme Sayfası";
    Layout = "~/Views/Shared/YoneticiLayout.cshtml";
}

<h2>Kullanıcılar</h2>

<p>
    <a href="@Url.Action("Ekle")" class="btn btn-primary">Kayıt Ekle</a>
</p>

<table class="table">
    <tr>
        <th>
            Rol Adı
        </th>
        <th>
            Adı
        </th>
        <th>
            Soyadı
        </th>
        <th>
            Kullanıcı Adı
        </th>
        <th>
            Şifresi
        </th>
        <th>
            Telefon Numarası
        </th>
        <th>
            E Posta Adresi
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.KullaniciRol.ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.soyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.kullaniciAd)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.sifre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefon)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ePosta)
            </td>
            <td>
                <a href="@Url.Action("Duzenle", new { id = item.kullaniciID })" class="btn btn-primary">Düzenle</a> |
                <a href="@Url.Action("Sil", new { id = item.kullaniciID })" class="btn btn-danger">Sil</a>
            </td>

        </tr>
    }

</table>