Models/Entities/Satis.cs
namespace EczaneDEMOo.Models.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Satis
    {
        [Key]
        public int satisID { get; set; }

        public int? ilacID { get; set; }
        public int? receteID { get; set; }
        public int? musteriID { get; set; }

        public int? calisanID { get; set; }

        [Column(TypeName = "smalldatetime")]
        public DateTime? satisTarih { get; set; }

        public int? miktar { get; set; }

        [Column(TypeName = "money")]
        public decimal? fiyat { get; set; }

        public virtual Ilac Ilac { get; set; }

        public virtual Kullanici Kullanici { get; set; }

        public virtual Musteri Musteri { get; set; }
    }
}

Controllers/AnasayfaController.cs
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Kullanici")]

    public class AnasayfaController : Controller
    {
        // GET: Anasayfa
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/SatisController.cs
using EczaneDEMOo.Models;
using EczaneDEMOo.Models.Entities;
using EczaneDEMOo.Session;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EczaneDEMOo.Controllers
{
    [CustomAuthorize(Role = "Kullanici")]

    public class SatisController : Controller
    {
        private readonly EczaneContext _context;

        public SatisController()
        {
            _context = new EczaneContext();
        }

        // GET: Satis
        public ActionResult Index()
        {
            var model = _context.Satis.ToList();// Tüm satışları getirir ve listeye dönüştürür
            return View(model);
        }

        public ActionResult RecetesizSatis()
        {
            #region Ilac Getirme
            // İlaçları getir ve SelectListItem nesnelerine dönüştür
            List<SelectListItem> selectListItems = _context.Ilac.Select(f => new SelectListItem
            {
                Value = f.ilacID.ToString(),
                Text = f.ad
            }).ToList();

            // SelectList oluşturuluyor

            SelectList selectList = new SelectList(selectListItems, "Value", "Text");

            // İlaç bilgisi ViewData'ya ekleniyor
            ViewData["Ilac"] = selectList;
            #endregion
            return View();// RecetesizSatis view'ını döner
        }

        // GET: ReceteNo
        [HttpGet]
        public ActionResult ReceteNoGir()
        {
            return View();
        }

        // POST: ReceteNo
        [HttpPost]
        public ActionResult ReceteNoGir(string receteNo)// ReceteNoGir aksiyon metodu, string parametre alır
        {
            if (!string.IsNullOrEmpty(receteNo))// Reçete numarası boş değilse
            {
                // ReceteNo'ya ait bilgileri veritabanından alın
                var recete = _context.Recete.SingleOrDefault(r => r.receteNo == receteNo);
                if (recete != null)// Reçete bulunursa
                {
                    var model = new SatisReceteSatisViewModel
                    {
                        ReceteNo = recete.receteNo,// Reçetenin numarası (receteNo) modelin ReceteNo alanına atanıyor
                        ReceteID = recete.receteID,
                        IlacID = recete.ilacID.Value,
                        Adet = recete.miktar.Value,
                        Fiyat = recete.Ilac.fiyat.Value
                    };

                    // Bilgi ve onay sayfasına yönlendir
                    return View("ReceteBilgiOnay", model);
                }

                ModelState.AddModelError("", "Geçerli bir reçete numarası bulunamadı.");
                return View();
            }

            ModelState.AddModelError("", "Reçete numarası boş olamaz.");
            return View();
        }

        // POST: Onayla
        [HttpPost]
        public ActionResult Onayla(SatisReceteSatisViewModel model)
        {
            if (ModelState.IsValid)// ModelState geçerli mi kontrolü
            {
                var recete = _context.Recete.Where(r => r.receteID == model.ReceteID).SingleOrDefault();
                // Satış işlemini veritabanına kaydet
                // Yeni bir Satis nesnesi oluştur ve modelden gelen verilerle doldur
                var satis = new Satis
                {
                    receteID = model.ReceteID,// Modelden gelen ReceteID'yi ata
                    ilacID = model.IlacID,
                    miktar = model.Adet,
                    fiyat = model.Fiyat * model.Adet,
                    satisTarih = DateTime.Now
                };

                _context.Satis.Add(satis);// Yeni satış ekle
                _context.SaveChanges();// Değişiklikleri kaydet

                return RedirectToAction("SatisBasarili");
            }

            return View("ReceteBilgiOnay", model);
        }

        public ActionResult SatisBasarili()
        {
            return View();
        }

        // ReceteBilgiOnay görünümünü aynı şekilde bıraktık
        public ActionResult ReceteBilgiOnay()
        {
            return View();
        }

        public ActionResult Ilac()
        {

            return View();
        }

    }
}

Views/Satis/Index.cshtml
@model IEnumerable<EczaneDEMOo.Models.Entities.Satis>

@{
    ViewBag.Title = "Satışlar Tablosu";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<table class="table">
    <tr>
        <th>
           Ilaç Adı
        </th>
        <th>
            Satıcı
        </th>
        <th>
            Musteri
        </th>
        <th>
            Satış Tarihi
        </th>
        <th>
            Satış Miktarı
        </th>
        <th>
            Satış Fiyatı
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Ilac.ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Kullanici.ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Musteri.adSoyad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.satisTarih)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.miktar)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.fiyat)
            </td>
        </tr>
    }

</table>

Views/Satis/ReceteBilgiOnay.cshtml
@model EczaneDEMOo.Models.SatisReceteSatisViewModel

@{
    ViewBag.Title = "Recete Bilgi Onay";
    Layout = "~/Views/Shared/Layout.cshtml";
}


<h2>   Reçete Bilgisi ve Onay</h2>

@using (Html.BeginForm("Onayla", "Satis", FormMethod.Post))
{
    <style>
        .content-wrapper {
            padding-left: 20px; /* İhtiyacınıza göre bu değeri ayarlayın */
        }
    </style>

    @Html.AntiForgeryToken()
    @Html.HiddenFor(model => model.ReceteNo)
    @Html.HiddenFor(model => model.ReceteID)
    @Html.HiddenFor(model => model.IlacID)
    @Html.HiddenFor(model => model.Adet)
    @Html.HiddenFor(model => model.Fiyat)

    <div class="form-group">
        <label>   Reçete No</label>
        <p>   @Model.ReceteNo</p>
    </div>

    <div class="form-group">
        <label>   İlacın Numarası</label>
        <p>   @Model.IlacID</p>
    </div>

    <div class="form-group">
        <label>   Adet</label>
        <p>   @Model.Adet</p>
    </div>

    <div class="form-group">
        <label>   Fiyat</label>
        <p>   @Model.Fiyat</p>
    </div>

    <button type="submit" class="btn btn-primary">   Satışı Onayla</button>
}

Views/Satis/ReceteNoGir.cshtml
@{
    ViewBag.Title = "ReceteNoGir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@{
    ViewBag.Title = "Reçete İle Satış";
}

<h2>Reçete Numarası Girme </h2>

@using (Html.BeginForm("ReceteNoGir", "Satis", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.Label("Reçete Numarası Gir")
        @Html.TextBox("receteNo", null, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Devam Et</button>
}

Views/Satis/ReceteSatis.cshtml
@model EczaneDEMOo.Models.SatisReceteSatisViewModel

@{
    ViewBag.Title = "ReceteSatis";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Reçete ile Satış</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.ReceteNo)
        @Html.TextBoxFor(model => model.ReceteNo, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ReceteNo)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IlacID)
        @Html.TextBoxFor(model => model.IlacID, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IlacID)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Adet)
        @Html.TextBoxFor(model => model.Adet, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Adet)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Fiyat)
        @Html.TextBoxFor(model => model.Fiyat, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Fiyat)
    </div>

    <button type="submit" class="btn btn-primary">Satış Yap</button>
}

Views/Satis/RecetesizSatis.cshtml
@model EczaneDEMOo.Models.Entities.Satis

@{
    ViewBag.Title = "Reçetesiz İlaç Satış";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Satış</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ilacID, "ilaç Adı", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ilacID", (SelectList)ViewData["Ilac"], htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ilacID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.miktar, "İlaç Miktarı",htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.miktar, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.miktar, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sat" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    <a href="@Url.Action("Index")" class="btn btn-secondary">Listeye Geri Dön</a>
</div>

Views/Satis/SatisBasarili.cshtml
@{
    ViewBag.Title = "Satış Başarılı";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<style>
    .content-wrapper {
        padding-left: 20px; /* İhtiyacınıza göre bu değeri ayarlayın */
    }
</style>

<h2>   Satış Başarılı</h2>

<p>   Satış işlemi başarılı bir şekilde tamamlandı.</p>

<p>   Ne yapmak istersiniz?</p>

<ul class="list-group">
    <li class="list-group-item">
        <a href="@Url.Action("Index", "Anasayfa")" class="btn btn-primary">  Ana Sayfaya Dön</a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("ReceteNoGir", "Satis")" class="btn btn-success">  Yeni Satış Yap</a>
    </li>
    <li class="list-group-item">
        <a href="@Url.Action("Index", "Satis")" class="btn btn-info">  Satışları Görüntüle</a>
    </li>
</ul>